/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;
import Vehiculos.EstadosVehiculo;
import Vehiculos.Vehiculo;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.awt.event.ActionListener;
import javax.sound.sampled.Clip;
import javax.swing.Timer;
/**
 *
 * @author 9569
 */
public class Conduccion extends javax.swing.JPanel {

    int cont = 0;
    int cont2= 0;
    int cont3= 0;
    
    Vehiculo vehiculo = new Vehiculo();
    Clip Motor_ON_Car = Sonido.Crear("D:\\USB-DENISEEM\\temp\\Proyecto Proga\\Proyecto1_Vehiculo_InfinityLoopers\\src\\GUI\\Sonidos\\Motor_ON_Car.wav");
    Clip Acceleration = Sonido.Crear("D:\\USB-DENISEEM\\temp\\Proyecto Proga\\Proyecto1_Vehiculo_InfinityLoopers\\src\\GUI\\Sonidos\\Acceleration_Car.wav");
    Clip Disacceleration = Sonido.Crear("D:\\USB-DENISEEM\\temp\\Proyecto Proga\\Proyecto1_Vehiculo_InfinityLoopers\\src\\GUI\\Sonidos\\Disacceleration_Car.wav");
    Clip ReversaWarning = Sonido.Crear("D:\\USB-DENISEEM\\temp\\Proyecto Proga\\Proyecto1_Vehiculo_InfinityLoopers\\src\\GUI\\Sonidos\\Warning_3.wav");
    Clip Warning = Sonido.Crear("D:\\USB-DENISEEM\\temp\\Proyecto Proga\\Proyecto1_Vehiculo_InfinityLoopers\\src\\GUI\\Sonidos\\Warning.wav");

    /**
     * Creates new form Conduccion
     */
    public Conduccion() {
        initComponents();
        ActualizarEstados.start();
        Acelerando.setInitialDelay(0);
        Desacelerando.setInitialDelay(0);
        System.out.println(vehiculo.getTransmision().getMarcha().getMARCHA());
    }
    
                Timer VerificarCarga = new Timer(0, new ActionListener() {
        public void actionPerformed(ActionEvent e) {
        if (vehiculo.getTanque().getEstado()<=0 || vehiculo.getBateria().getCarga() <=0) {
            VerificarCarga.stop();
            vehiculo.setEstado(EstadosVehiculo.APAGADO);
            vehiculo.getTransmision().setNeutro();
            vehiculo.Desacelerar();
            Acelerando.stop();
            Desacelerando.start();
            Sonido.Detener(Acceleration);
            Sonido.Iniciar(Warning, 0);
        }
        }
    });
            
            Timer SonidoReverda = new Timer(700, new ActionListener() {
        public void actionPerformed(ActionEvent e) {
        Sonido.Iniciar(ReversaWarning, 0);
        }
    });
    
        Timer Acelerando = new Timer(4000, new ActionListener() {
        public void actionPerformed(ActionEvent e) {
        Sonido.Iniciar(Acceleration, cont);
        System.out.println(cont);
        System.out.println(cont2 + " ACC");
        cont = cont + 4000000;
        cont2 = (int)((double) cont/52000000*100);
        cont3 = (int)((double)18000000*((double)((double)100-cont2)/100));
        
        if (cont == 52000000) {
           cont = 44000000;
        }
        }
    });
        
            Timer Desacelerando = new Timer(1000, new ActionListener() {
        public void actionPerformed(ActionEvent e) {
        Sonido.Iniciar(Disacceleration, cont3);
        cont3 = cont3 + 1000000;
        cont = cont - 4000000;
        System.out.println(cont3 + "DISACC");
        if (cont <= 0) {
            Desacelerando.stop();
            cont = 0;
        }
    }
    });

        Timer ActualizarEstados = new Timer(0, new ActionListener() {
    public void actionPerformed(ActionEvent e) {        
        JTF_Velocimetro.setText(String.valueOf(vehiculo.getVelocimetro()));
        JTF_RPM.setText(String.valueOf(vehiculo.getMotor().getRPMActual()));
        JTF_EstadoGasolina.setText(String.valueOf(vehiculo.getTanque().getEstado()));
        JTF_EstadoGasolina.setText(String.valueOf(vehiculo.getTanque().getEstado()));
        JTF_Kilometraje.setText(String.valueOf(vehiculo.getKilometraje()));
        JTF_EstadoBateria.setText(String.valueOf(vehiculo.getBateria().getCarga()));
        JTF_Marcha.setText(String.valueOf(vehiculo.getTransmision().getMarcha()));
        JPB_Gasolina.setValue((int)vehiculo.getTanque().getEstado());
        JPB_Bateria.setValue((int)vehiculo.getBateria().getCarga());
        vehiculo.getTanque().AdvertirGasolinaBaja(vehiculo.getTanque().getEstado());
    }
    });  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPB_Bateria = new javax.swing.JProgressBar();
        JTF_Marcha = new javax.swing.JTextField();
        JTB_ActionButton = new javax.swing.JToggleButton();
        JTF_Velocimetro = new javax.swing.JTextField();
        JTF_RPM = new javax.swing.JTextField();
        JTF_EstadoGasolina = new javax.swing.JTextField();
        JTF_Kilometraje = new javax.swing.JTextField();
        JTF_EstadoBateria = new javax.swing.JTextField();
        JB_LlenarTanque = new javax.swing.JButton();
        JB_CambiarBateria = new javax.swing.JButton();
        JPB_Gasolina = new javax.swing.JProgressBar();

        JPB_Bateria.setString("100");

        JTF_Marcha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTF_Marcha.setText("0");
        JTF_Marcha.setEnabled(false);
        JTF_Marcha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTF_MarchaActionPerformed(evt);
            }
        });

        JTB_ActionButton.setText("iiiiiiiiiii");
        JTB_ActionButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JTB_ActionButtonKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JTB_ActionButtonKeyReleased(evt);
            }
        });

        JTF_Velocimetro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTF_Velocimetro.setText("0");
        JTF_Velocimetro.setEnabled(false);

        JTF_RPM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTF_RPM.setText("0");
        JTF_RPM.setEnabled(false);
        JTF_RPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTF_RPMActionPerformed(evt);
            }
        });

        JTF_EstadoGasolina.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTF_EstadoGasolina.setText("0");
        JTF_EstadoGasolina.setEnabled(false);
        JTF_EstadoGasolina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTF_EstadoGasolinaActionPerformed(evt);
            }
        });

        JTF_Kilometraje.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTF_Kilometraje.setText("0");
        JTF_Kilometraje.setEnabled(false);
        JTF_Kilometraje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTF_KilometrajeActionPerformed(evt);
            }
        });

        JTF_EstadoBateria.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTF_EstadoBateria.setText("0");
        JTF_EstadoBateria.setEnabled(false);
        JTF_EstadoBateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTF_EstadoBateriaActionPerformed(evt);
            }
        });

        JB_LlenarTanque.setText("LlenarTanque");
        JB_LlenarTanque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_LlenarTanqueActionPerformed(evt);
            }
        });

        JB_CambiarBateria.setText("CambiarBateria");
        JB_CambiarBateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_CambiarBateriaActionPerformed(evt);
            }
        });

        JPB_Gasolina.setString("100");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JTF_Kilometraje, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(JTF_Velocimetro, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(JTB_ActionButton))
                            .addComponent(JTF_RPM, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(JTF_EstadoGasolina, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(JPB_Gasolina, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(JTF_EstadoBateria, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(JPB_Bateria, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(JTF_Marcha, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JB_CambiarBateria)
                                    .addComponent(JB_LlenarTanque, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JTF_RPM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JTF_EstadoGasolina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(JPB_Gasolina, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JPB_Bateria, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JTF_Velocimetro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JTF_EstadoBateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTF_Kilometraje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTF_Marcha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTB_ActionButton)
                    .addComponent(JB_LlenarTanque))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JB_CambiarBateria)
                .addContainerGap(96, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void JTF_MarchaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTF_MarchaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTF_MarchaActionPerformed

    private void JTB_ActionButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTB_ActionButtonKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_W){
            if (vehiculo.getEstado() == vehiculo.getEstado().MARCHA && vehiculo.getTransmision().getMarcha() != vehiculo.getTransmision().getMarcha().NEUTRO && vehiculo.getTransmision().getMarcha() != vehiculo.getTransmision().getMarcha().REVERSA) {
                vehiculo.Acelerar();
                Acelerando.start();
                Desacelerando.stop();
                Sonido.Detener(Disacceleration);
            }
        }
        if (evt.getKeyCode() == KeyEvent.VK_S){
            vehiculo.Frenar();
            if (vehiculo.getTransmision().getMarcha() == vehiculo.getTransmision().getMarcha().REVERSA){
                SonidoReverda.start();
            }
        }
        if (evt.getKeyCode() == KeyEvent.VK_SPACE){
            vehiculo.getTransmision().PresionarEmbrague();
        }
        if (evt.getKeyCode() == KeyEvent.VK_1){
            vehiculo.getTransmision().setMarcha1();
        }
        if (evt.getKeyCode() == KeyEvent.VK_2){
            vehiculo.getTransmision().setMarcha2();
        }
        if (evt.getKeyCode() == KeyEvent.VK_3){
            vehiculo.getTransmision().setMarcha3();
        }
        if (evt.getKeyCode() == KeyEvent.VK_4){
            vehiculo.getTransmision().setMarcha4();
        }
        if (evt.getKeyCode() == KeyEvent.VK_5){
            vehiculo.getTransmision().setMarcha5();
        }
        if (evt.getKeyCode() == KeyEvent.VK_R){
            vehiculo.getTransmision().setReversa();
        }
        if (evt.getKeyCode() == KeyEvent.VK_N){
            vehiculo.getTransmision().setNeutro();
        }
        if (evt.getKeyCode() == KeyEvent.VK_TAB){
            VerificarCarga.start();
            vehiculo.setMarcha();
            Sonido.Iniciar(Motor_ON_Car, 0);
        }
        if (evt.getKeyCode() == KeyEvent.VK_CAPS_LOCK){
            VerificarCarga.start();
            vehiculo.setIgnicion();
        }
        if (evt.getKeyCode() == KeyEvent.VK_SHIFT){
            vehiculo.setApagar();
        }
    }//GEN-LAST:event_JTB_ActionButtonKeyPressed

    private void JTB_ActionButtonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTB_ActionButtonKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_W){
            if (vehiculo.getEstado() == vehiculo.getEstado().MARCHA && vehiculo.getTransmision().getMarcha() != vehiculo.getTransmision().getMarcha().REVERSA) {
                vehiculo.Desacelerar();
                Acelerando.stop();
                Desacelerando.start();
            }
            Sonido.Detener(Acceleration);
        }
        if (evt.getKeyCode() == KeyEvent.VK_S){
            if (vehiculo.getTransmision().getMarcha() == vehiculo.getTransmision().getMarcha().REVERSA){
                SonidoReverda.stop();
            }
        }
        vehiculo.getTransmision().SoltarEmbrague();
    }//GEN-LAST:event_JTB_ActionButtonKeyReleased

    private void JTF_RPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTF_RPMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTF_RPMActionPerformed

    private void JTF_EstadoGasolinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTF_EstadoGasolinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTF_EstadoGasolinaActionPerformed

    private void JTF_KilometrajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTF_KilometrajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTF_KilometrajeActionPerformed

    private void JTF_EstadoBateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTF_EstadoBateriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTF_EstadoBateriaActionPerformed

    private void JB_LlenarTanqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_LlenarTanqueActionPerformed
        vehiculo.getTanque().LlenarTanque();
    }//GEN-LAST:event_JB_LlenarTanqueActionPerformed

    private void JB_CambiarBateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_CambiarBateriaActionPerformed
        vehiculo.getBateria().CambiarBateria();
    }//GEN-LAST:event_JB_CambiarBateriaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_CambiarBateria;
    private javax.swing.JButton JB_LlenarTanque;
    private javax.swing.JProgressBar JPB_Bateria;
    private javax.swing.JProgressBar JPB_Gasolina;
    private javax.swing.JToggleButton JTB_ActionButton;
    private javax.swing.JTextField JTF_EstadoBateria;
    private javax.swing.JTextField JTF_EstadoGasolina;
    private javax.swing.JTextField JTF_Kilometraje;
    private javax.swing.JTextField JTF_Marcha;
    private javax.swing.JTextField JTF_RPM;
    private javax.swing.JTextField JTF_Velocimetro;
    // End of variables declaration//GEN-END:variables
}
