/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;
import Vehiculos.EstadosVehiculo;
import Vehiculos.Vehiculo;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.awt.event.ActionListener;
import javax.sound.sampled.Clip;
import javax.swing.Timer;
/**
 *
 * @author 9569
 */
public class Cond1 extends javax.swing.JPanel {

    int cont = 0;
    int cont2= 0;
    int cont3= 0;
    
    Vehiculo vehiculo = new Vehiculo();
    Clip Motor_ON_Car = Sonido.Crear("D:\\USB-DENISEEM\\temp\\Proyecto Proga\\Proyecto1_Vehiculo_InfinityLoopers\\src\\GUI\\Sonidos\\Motor_ON_Car.wav");
    Clip Acceleration = Sonido.Crear("D:\\USB-DENISEEM\\temp\\Proyecto Proga\\Proyecto1_Vehiculo_InfinityLoopers\\src\\GUI\\Sonidos\\Acceleration_Car.wav");
    Clip Disacceleration = Sonido.Crear("D:\\USB-DENISEEM\\temp\\Proyecto Proga\\Proyecto1_Vehiculo_InfinityLoopers\\src\\GUI\\Sonidos\\Disacceleration_Car.wav");
    Clip ReversaWarning = Sonido.Crear("D:\\USB-DENISEEM\\temp\\Proyecto Proga\\Proyecto1_Vehiculo_InfinityLoopers\\src\\GUI\\Sonidos\\Warning_3.wav");
    Clip Warning = Sonido.Crear("D:\\USB-DENISEEM\\temp\\Proyecto Proga\\Proyecto1_Vehiculo_InfinityLoopers\\src\\GUI\\Sonidos\\Warning.wav");

    /**
     * Creates new form Conduccion
     */
    public Cond1() {
        initComponents();
        ActualizarEstados.start();
        Acelerando.setInitialDelay(0);
        Desacelerando.setInitialDelay(0);
        System.out.println(vehiculo.getTransmision().getMarcha().getMARCHA());
    }
    
                Timer VerificarCarga = new Timer(0, new ActionListener() {
        public void actionPerformed(ActionEvent e) {
        if (vehiculo.getTanque().getEstado()<=0 || vehiculo.getBateria().getCarga() <=0) {
            VerificarCarga.stop();
            vehiculo.setEstado(EstadosVehiculo.APAGADO);
            vehiculo.getTransmision().setNeutro();
            vehiculo.Desacelerar();
            Acelerando.stop();
            Desacelerando.start();
            Sonido.Detener(Acceleration);
            Sonido.Iniciar(Warning, 0);
        }
        }
    });
            
            Timer SonidoReverda = new Timer(700, new ActionListener() {
        public void actionPerformed(ActionEvent e) {
        Sonido.Iniciar(ReversaWarning, 0);
        }
    });
    
        Timer Acelerando = new Timer(4000, new ActionListener() {
        public void actionPerformed(ActionEvent e) {
        Sonido.Iniciar(Acceleration, cont);
        System.out.println(cont);
        System.out.println(cont2 + " ACC");
        cont = cont + 4000000;
        cont2 = (int)((double) cont/52000000*100);
        cont3 = (int)((double)18000000*((double)((double)100-cont2)/100));
        
        if (cont == 52000000) {
           cont = 44000000;
        }
        }
    });
        
            Timer Desacelerando = new Timer(1000, new ActionListener() {
        public void actionPerformed(ActionEvent e) {
        Sonido.Iniciar(Disacceleration, cont3);
        cont3 = cont3 + 1000000;
        cont = cont - 4000000;
        System.out.println(cont3 + "DISACC");
        if (cont <= 0) {
            Desacelerando.stop();
            cont = 0;
        }
    }
    });

        Timer ActualizarEstados = new Timer(0, new ActionListener() {
    public void actionPerformed(ActionEvent e) {        
        JTF_Velocimetro.setText(String.valueOf(vehiculo.getVelocimetro()));
        JTF_RPM.setText(String.valueOf(vehiculo.getMotor().getRPMActual()));
        JTF_Kilometraje.setText(String.valueOf(vehiculo.getKilometraje()));
        JTF_Marcha.setText(String.valueOf(vehiculo.getTransmision().getMarcha()));
        JPB_Gasolina.setValue((int)vehiculo.getTanque().getEstado());
        JPB_Bateria.setValue((int)vehiculo.getBateria().getCarga());
        vehiculo.getTanque().AdvertirGasolinaBaja(vehiculo.getTanque().getEstado());
    }
    });  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JTF_Kilometraje = new javax.swing.JTextField();
        JB_LlenarTanque = new javax.swing.JButton();
        JB_CambiarBateria = new javax.swing.JButton();
        JPB_Gasolina = new javax.swing.JProgressBar();
        JPB_Bateria = new javax.swing.JProgressBar();
        JTF_Marcha = new javax.swing.JTextField();
        JTB_ActionButton = new javax.swing.JToggleButton();
        JTF_Velocimetro = new javax.swing.JTextField();
        JTF_RPM = new javax.swing.JTextField();
        JL_Velocimetro = new javax.swing.JLabel();
        JL_RPM1 = new javax.swing.JLabel();
        JL_RPM2 = new javax.swing.JLabel();
        JL_RPM3 = new javax.swing.JLabel();
        JL_RPM4 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(780, 290));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JTF_Kilometraje.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JTF_Kilometraje.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTF_Kilometraje.setText("0");
        JTF_Kilometraje.setEnabled(false);
        JTF_Kilometraje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTF_KilometrajeActionPerformed(evt);
            }
        });
        jPanel1.add(JTF_Kilometraje, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 190, -1));

        JB_LlenarTanque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Img/RecargarGasolina.png"))); // NOI18N
        JB_LlenarTanque.setText("LlenarTanque");
        JB_LlenarTanque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_LlenarTanqueActionPerformed(evt);
            }
        });
        jPanel1.add(JB_LlenarTanque, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, -1, 40));

        JB_CambiarBateria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Img/CambiarBateria.png"))); // NOI18N
        JB_CambiarBateria.setText("CambiarBateria");
        JB_CambiarBateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_CambiarBateriaActionPerformed(evt);
            }
        });
        jPanel1.add(JB_CambiarBateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, -1, 40));

        JPB_Gasolina.setString("100");
        jPanel1.add(JPB_Gasolina, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 140, 13));

        JPB_Bateria.setString("100");
        jPanel1.add(JPB_Bateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 190, 13));

        JTF_Marcha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTF_Marcha.setText("-");
        JTF_Marcha.setEnabled(false);
        JTF_Marcha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTF_MarchaActionPerformed(evt);
            }
        });
        jPanel1.add(JTF_Marcha, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 120, -1));

        JTB_ActionButton.setText("Conducir");
        JTB_ActionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTB_ActionButtonActionPerformed(evt);
            }
        });
        JTB_ActionButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JTB_ActionButtonKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JTB_ActionButtonKeyReleased(evt);
            }
        });
        jPanel1.add(JTB_ActionButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        JTF_Velocimetro.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        JTF_Velocimetro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTF_Velocimetro.setText("0");
        JTF_Velocimetro.setEnabled(false);
        jPanel1.add(JTF_Velocimetro, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 73, -1));

        JTF_RPM.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        JTF_RPM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTF_RPM.setText("0");
        JTF_RPM.setEnabled(false);
        JTF_RPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTF_RPMActionPerformed(evt);
            }
        });
        jPanel1.add(JTF_RPM, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 150, 100, -1));

        JL_Velocimetro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Img/Velocimetro.png"))); // NOI18N
        jPanel1.add(JL_Velocimetro, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        JL_RPM1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Img/Apagado.png"))); // NOI18N
        jPanel1.add(JL_RPM1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, -1, -1));

        JL_RPM2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Img/RPM.png"))); // NOI18N
        jPanel1.add(JL_RPM2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 70, -1, -1));

        JL_RPM3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Img/Bateria.png"))); // NOI18N
        jPanel1.add(JL_RPM3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        JL_RPM4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Img/Gasolina.png"))); // NOI18N
        jPanel1.add(JL_RPM4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void JTF_MarchaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTF_MarchaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTF_MarchaActionPerformed

    private void JTB_ActionButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTB_ActionButtonKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_W){
            if (vehiculo.getEstado() == vehiculo.getEstado().MARCHA && vehiculo.getTransmision().getMarcha() != vehiculo.getTransmision().getMarcha().NEUTRO && vehiculo.getTransmision().getMarcha() != vehiculo.getTransmision().getMarcha().REVERSA) {
                vehiculo.Acelerar();
                Acelerando.start();
                Desacelerando.stop();
                Sonido.Detener(Disacceleration);
            }
        }
        if (evt.getKeyCode() == KeyEvent.VK_S){
            vehiculo.Frenar();
            if (vehiculo.getTransmision().getMarcha() == vehiculo.getTransmision().getMarcha().REVERSA){
                SonidoReverda.start();
            }
        }
        if (evt.getKeyCode() == KeyEvent.VK_SPACE){
            vehiculo.getTransmision().PresionarEmbrague();
        }
        if (evt.getKeyCode() == KeyEvent.VK_1){
            vehiculo.getTransmision().setMarcha1();
        }
        if (evt.getKeyCode() == KeyEvent.VK_2){
            vehiculo.getTransmision().setMarcha2();
        }
        if (evt.getKeyCode() == KeyEvent.VK_3){
            vehiculo.getTransmision().setMarcha3();
        }
        if (evt.getKeyCode() == KeyEvent.VK_4){
            vehiculo.getTransmision().setMarcha4();
        }
        if (evt.getKeyCode() == KeyEvent.VK_5){
            vehiculo.getTransmision().setMarcha5();
        }
        if (evt.getKeyCode() == KeyEvent.VK_R){
            vehiculo.getTransmision().setReversa();
        }
        if (evt.getKeyCode() == KeyEvent.VK_N){
            vehiculo.getTransmision().setNeutro();
        }
        if (evt.getKeyCode() == KeyEvent.VK_TAB){
            VerificarCarga.start();
            vehiculo.setMarcha();
            Sonido.Iniciar(Motor_ON_Car, 0);
            JL_RPM1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Img/Marcha.png")));
        }
        if (evt.getKeyCode() == KeyEvent.VK_CAPS_LOCK){
            VerificarCarga.start();
            vehiculo.setIgnicion();
            JL_RPM1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Img/Ignicion.png")));
        }
        if (evt.getKeyCode() == KeyEvent.VK_SHIFT){
            vehiculo.setApagar();
            JL_RPM1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Img/Apagado.png")));
        }
    }//GEN-LAST:event_JTB_ActionButtonKeyPressed

    private void JTB_ActionButtonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTB_ActionButtonKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_W){
            if (vehiculo.getEstado() == vehiculo.getEstado().MARCHA && vehiculo.getTransmision().getMarcha() != vehiculo.getTransmision().getMarcha().REVERSA) {
                vehiculo.Desacelerar();
                Acelerando.stop();
                Desacelerando.start();
            }
            Sonido.Detener(Acceleration);
        }
        if (evt.getKeyCode() == KeyEvent.VK_S){
            if (vehiculo.getTransmision().getMarcha() == vehiculo.getTransmision().getMarcha().REVERSA){
                SonidoReverda.stop();
            }
        }
        vehiculo.getTransmision().SoltarEmbrague();
    }//GEN-LAST:event_JTB_ActionButtonKeyReleased

    private void JTF_RPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTF_RPMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTF_RPMActionPerformed

    private void JTF_KilometrajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTF_KilometrajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTF_KilometrajeActionPerformed

    private void JB_LlenarTanqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_LlenarTanqueActionPerformed
        vehiculo.getTanque().LlenarTanque();
    }//GEN-LAST:event_JB_LlenarTanqueActionPerformed

    private void JB_CambiarBateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_CambiarBateriaActionPerformed
        vehiculo.getBateria().CambiarBateria();
    }//GEN-LAST:event_JB_CambiarBateriaActionPerformed

    private void JTB_ActionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTB_ActionButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTB_ActionButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_CambiarBateria;
    private javax.swing.JButton JB_LlenarTanque;
    private javax.swing.JLabel JL_RPM1;
    private javax.swing.JLabel JL_RPM2;
    private javax.swing.JLabel JL_RPM3;
    private javax.swing.JLabel JL_RPM4;
    private javax.swing.JLabel JL_Velocimetro;
    private javax.swing.JProgressBar JPB_Bateria;
    private javax.swing.JProgressBar JPB_Gasolina;
    private javax.swing.JToggleButton JTB_ActionButton;
    private javax.swing.JTextField JTF_Kilometraje;
    private javax.swing.JTextField JTF_Marcha;
    private javax.swing.JTextField JTF_RPM;
    private javax.swing.JTextField JTF_Velocimetro;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
