/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import Vehiculos.Vehiculo;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
/**
 *
 * @author 9569
 */
public class FRMVehiculo extends javax.swing.JFrame {

    Vehiculo vehiculo = new Vehiculo();
    /**
     * Creates new form FRMVehiculo
     */
    public FRMVehiculo() {
        initComponents();
        ActualizarEstados.start();
        
        vehiculo.setMarcha();
        System.out.println(vehiculo.getTransmision().getMarcha().getMARCHA());
    }

        Timer ActualizarEstados = new Timer(0, new ActionListener() {
    public void actionPerformed(ActionEvent e) {        
        JTF_Velocimetro.setText(String.valueOf(vehiculo.getVelocimetro()));
        JTF_RPM.setText(String.valueOf(vehiculo.getMotor().getRPMActual()));
    }
    });  
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JTB_ActionButton = new javax.swing.JToggleButton();
        JTF_Velocimetro = new javax.swing.JTextField();
        JTF_RPM = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JTB_ActionButton.setText("Acelerar");
        JTB_ActionButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JTB_ActionButtonKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JTB_ActionButtonKeyReleased(evt);
            }
        });

        JTF_Velocimetro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTF_Velocimetro.setText("0");
        JTF_Velocimetro.setEnabled(false);

        JTF_RPM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTF_RPM.setText("0");
        JTF_RPM.setEnabled(false);
        JTF_RPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTF_RPMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JTF_RPM, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTF_Velocimetro, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTB_ActionButton))
                .addContainerGap(321, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JTF_RPM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(JTF_Velocimetro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(JTB_ActionButton)
                .addContainerGap(211, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTF_RPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTF_RPMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTF_RPMActionPerformed

    private void JTB_ActionButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTB_ActionButtonKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_W){
        vehiculo.Acelerar();        
        }
        if (evt.getKeyCode() == KeyEvent.VK_S){
        vehiculo.Frenar();
        }
        if (evt.getKeyCode() == KeyEvent.VK_SPACE){
        vehiculo.getTransmision().PresionarEmbrague();
        }
        if (evt.getKeyCode() == KeyEvent.VK_1){
        vehiculo.getTransmision().setMarcha1();
        }
        if (evt.getKeyCode() == KeyEvent.VK_2){
        vehiculo.getTransmision().setMarcha2();
        }
        if (evt.getKeyCode() == KeyEvent.VK_3){
        vehiculo.getTransmision().setMarcha3();
        }
        if (evt.getKeyCode() == KeyEvent.VK_4){
        vehiculo.getTransmision().setMarcha4();
        }
        if (evt.getKeyCode() == KeyEvent.VK_5){
        vehiculo.getTransmision().setMarcha5();
        }
        if (evt.getKeyCode() == KeyEvent.VK_R){
        vehiculo.getTransmision().setReversa();
        }
        if (evt.getKeyCode() == KeyEvent.VK_N){
        vehiculo.getTransmision().setNeutro();
        }
    }//GEN-LAST:event_JTB_ActionButtonKeyPressed

    private void JTB_ActionButtonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTB_ActionButtonKeyReleased
        vehiculo.Desacelerar();
        vehiculo.getTransmision().SoltarEmbrague();
    }//GEN-LAST:event_JTB_ActionButtonKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRMVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRMVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRMVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRMVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRMVehiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton JTB_ActionButton;
    private javax.swing.JTextField JTF_RPM;
    private javax.swing.JTextField JTF_Velocimetro;
    // End of variables declaration//GEN-END:variables
}
